:PROPERTIES:
:ID:       c9318d48-6dc8-49ea-b2cb-5c4ce97469ab
:END:
#+title: Emacs Notes

* Search
** In a File
Search a line in open buffer: space ss or space ,
Search Headers: consult-imenu / space si

Search a word online: K or space so
** Files
space space to search all files in current directory.

Also use =consult-riprep= to search any string in all files in current directory.

*** Logseq like features
If you want logseq like tagging and being able to find those tagged blocks:

Set:
(setq org-agenda-files '("~/org"))

Find what you want:
M-x org-tags-view

Query examples:
test
test+bug
test|idea

check out note: [[file:logseqlike.md][Logseq Like Workflow]] 

* Buffers
Switch to buffer: space bb

* Bookmarks
Add a bookmark: space bm
Bookmark jump: space enter

* Narrow and Widen back a region
Narrow a selection: C-x nn
Widen back the narrowed selection: C-x nw

* Org Roam Related
** Add an alias to note file
#+begin_src
:PROPERTIES:
:ROAM_ALIASES: My Alias
:END:
#+end_src
** Create an Id for a header
org-id-get-create

How to connect id tagged header to another note?
Same as linking any other note. For keybindings of Org Roam check below link: 

[[file:~/.emacs.d/config.org::*Org Roam][Org Roam config]]

Example to add file and chapter link. This is for a file that is not inside org-roam database. It is a regular file.

#+BEGIN_SRC emacs-lisp
[[file:~/.emacs.d/config.org::#org-roam][Org Roam config]]
#+END_SRC

For org-roam connection. These are config.org keybindings.

  "nf" '(org-roam-node-find :which-key "find note")
  "nc" '(org-roam-capture :which-key "create note"))

** Note Id's
In order to see note id's, go to PROPERTIES and hit TAB.

* Projectile
** Find a file in project:
Once project folder is open: space pf or space space

* Lsp
** Keybindings
Enable lsp wiht: lsp
Goto definition: gd or space cd
Go back from definition: xref-go-back
** find functions
space si (This is better than M-x: imenu because it shows results while you navigate too.)
* Images
Below is great documentation for images in emacs.
https://signor.dev/simple-inline-images-in-org-mode/

* Link Files
org-insert-link

* Yasnippet
* Creating a YASnippet for Org Mode

** Create a new snippet

Run:

#+begin_src elisp
M-x yas-new-snippet
#+end_src

A new buffer opens.

** Example snippet

Paste this:

#+BEGIN_SRC emacs-lisp
  
  ,#+begin_src snippet
  # -*- mode: snippet -*-
  # name: org-roam book note
  # key: book
  # --

  ,#+title: ${1:Book Title}

  :PROPERTIES:
  :TYPE:     book
  :AUTHOR:   ${2:Author}
  :STATUS:   ${3:unread}
  :ROAM_REFS: ${4:isbn:}
  :END:

   Summary

  $0

   Key Ideas

   Quotes

   Connections
#+end_src

*** Save the snippet

Press:

#+begin_src text
C-x C-s
#+end_src

Save it to:

#+begin_src text
~/.emacs.d/snippets/org-mode/book
#+end_src

*** Reload snippets

#+begin_src elisp
M-x yas-reload-all
#+end_src

*** Use the snippet

Inside an Org file:

#+begin_src text
book TAB
#+end_src

It expands into a complete book note template.

#+END_SRC

* Code Block
You can name code blocks, so if it doesnt run you can see what block that failed. In order to name the block of code in org file, use: =+NAME: example code=


* Tags
** Add tags to a header
Use : at the beginning and end of the tagname. Ex: =:example:=
** Exlucde Tags to be exported
If you want to exclude certain tags to be excluded when exporting a doctument to another format, use: =#+EXCLUDE: something anotherone= in the header section, up top of the document.

