:PROPERTIES:
:ID:       4183EFD0-2246-44B0-9BDC-5BE011C8F76D
:END:
#+title: Java

* Design Patterns
https://m.youtube.com/watch?v=DtE3YNkVTao&ra=m

** Factory Design Pattern
*** Overview
The Factory Design Pattern is a creational pattern that centralizes object creation and hides the exact class being created from the client. This allows the calling code to create objects without knowing the exact class being instantiated.

Instead of using the new keyword directly, the client requests objects from a factory, and the factory chooses which concreate implementation to return.

It is useful when object creation is complex or when you want your system to be flexible, maintanable, and loosely coupled.

The Factory Pattern helps replace tight coupling with clean abstraction, making your project easier to extend and easier to modify as requirements change.
*** Example Code

**** Create a Notification interface
  #+BEGIN_SRC java
    interface Notification{
        void sendMessage(String msg);
        }
  #+END_SRC
  
**** Create 2 classes that implement that interface

  #+BEGIN_SRC java
    class EmailNotification implements Notification{
        @Override
        void sendMessage(String msg){
    	System.out.println("Sending Email: " + msg);
    	}
        }
  #+END_SRC

  
  #+BEGIN_SRC java
    class SMSNotification implements Notification{
        @Override
        void sendMessage(String msg){
    	System.out.println("Sending SMS: " + msg);
    	}
        }
  #+END_SRC

**** Now comes the core part
- Exact class is not exposed to the client.
  
    #+BEGIN_SRC java
      class NotificationFactory {
          public static Notification createNotification(String type){
      	//Based on type passed, create an object
      	if(type.equalsIgnoreCase("Email")){
      	    return new EmailNotification();
      	}else(type.equalsIgnoreCase("SMS")){
      		return new SMSNotification();
      	    }
      	return null;
          }
      }
    #+END_SRC
    
**** Main method to create the actual object
   #+BEGIN_SRC java
     public class FactoryPatternDemo{
         public static void main(String[] args){

     	Notification N1 = NotificationFactory.createNotification("EMAIL");
     	N1.sendMessage("Welcome to java factory pattern");
     	
     	Notification N2 = NotificationFactory.createNotification("SMS");
     	N2.sendMessage("OTP sent successfully");
     	
     	}
         }

   #+END_SRC
   
*** When to Use the Factory Pattern

- Hide the concrete class from the client.
- When object creation may change in the future.
- Add new object types without modifying client code.
- Choose which object to create at runtime.
- Common in large applications (e.g., database connections, parsers, drivers, UI components, validators, loggers, and frameworks like Spring).

** Builder Design Pattern
*** Overview
- It is an creational pattern used to construct complex objects step by step while keeping full control over the construction process.
- It is usefull when an object has many fields, especially optional fields, and constructor becomes too large or confusing.
- Instead of creating many constructors with different parameter combinations, the Builder pattern provides a clean, readable, and flexible way to create objects using method chaining.
- Builder solves the telescoping constructor problem(too many constructors problem) by letting you set only the values you need.
- It helps you create objects like "a User with name, email, address, and phone number" without forcing you to fill every parameter.

*** Example Code
#+BEGIN_SRC java
  class User{
      private String name;
      private String email;
      private String phone;
      private String address;

      private User (Builder builder){
  	this.name = builder.name;
  	this.email= builder.email;
  	this.phone= builder.phone;
  	this.address= builder.address;
    }
      //inner class
      //It contains same fields as User class
      public static class Builder{
  	private String name;
  	private String email;
  	private String phone;
  	private String address;

  	//Every method inside Builder sets one field at a time and returns Builder object itself. This allows method chaining.
  	public Builder setName(String name){
  	    this.name = name;
  	    return;
  	 }

  	public Builder setEmail(String email){
  	    this.email = email;
  	    return;
  	 }
  	
  	public Builder setPhone(String phone){
  	    this.phone = phone;
  	    return;
  	 }

  	public Builder setAddress(String address){
  	    this.address = address;
  	    return;
  	 }

  	
  	public User build(){
  	    //Create a User object and pass builder to constructor.
  	    //User Constructor (above) is private and you can not directly call User.
  	    //You must use Builder, this insures controlled creation. 
  	    return new User(this);
  	}

  	public void show(){
  	    System.out.println("User details:");
  	    System.out.println(name + ", " + email + ", " + phone + ", " + address);
  	}
      }//end Builder

  }
#+END_SRC

- Main Method
  #+BEGIN_SRC java
    public class BuilderPatternDemo{
        public static void main(String[] args){
    	User u1 = new User.Builder()
    	    .setName("Abe")
    	    .setEmail("xalil@gmail.com")
    	    .setPhone("999-765-2134")
    	    .build(); //build() method creates the final object with fields we provided. 

    	u1.show();
    	}

        }
  #+END_SRC

*** When should you use the Builder Pattern?
- Use the Builder pattern when a class has many fields, especially when some fields are optional and others are required.
- Use when constructor with many parameters becomes confusing or error-prone.
- Use it when your object should be immutable, since the builder can prepare all values and then create the final object only once.
- Use it when number of parameters increases and the code becomes harder to read.
- The Builder pattern is widely used in Spring Boot, Hibernate, Lambok's @Builder, HTTP client, database query builders, and most modern java libraries.
*** Resources
https://youtu.be/DtE3YNkVTao?si=0JZHaNnoOuoRuaXZ&t=320
* System Design
https://www.youtube.com/watch?v=s9Qh9fWeOAk
