:PROPERTIES:
:ID:       c9318d48-6dc8-49ea-b2cb-5c4ce97469ab
:END:
#+title: Emacs Notes

* Search
** In a File
Search a line in open buffer: space ss or space ,
Search Headers: consult-imenu / space si

Search a word online: K or space so
** Files
space space to search all files in current directory.

Also use =consult-riprep= to search any string in all files in current directory.

* Buffers
Switch to buffer: space bb

* Bookmarks
Add a bookmark: space bm
Bookmark jump: space enter

* Narrow and Widen back a region
Narrow a selection: C-x nn
Widen back the narrowed selection: C-x nw

* Org Roam Related
** Add an alias to note file
#+begin_src
:PROPERTIES:
:ROAM_ALIASES: My Alias
:END:
#+end_src
** Create an Id for a header
org-id-get-create

How to connect id tagged header to another note?
Same as linking any other note. For keybindings of Org Roam check below link: 

[[file:~/.emacs.d/config.org::*Org Roam][Org Roam config]]

Example to add file and chapter link. This is for a file that is not inside org-roam database. It is a regular file.

#+BEGIN_SRC emacs-lisp
[[file:~/.emacs.d/config.org::#org-roam][Org Roam config]]
#+END_SRC

For org-roam connection. These are config.org keybindings.

  "nf" '(org-roam-node-find :which-key "find note")
  "nc" '(org-roam-capture :which-key "create note"))

** Note Id's
In order to see note id's, go to PROPERTIES and hit TAB.

* Projectile
** Find a file in project:
Once project folder is open: space pf or space space

* Lsp
** Keybindings
Enable lsp wiht: lsp
Goto definition: gd or space cd
Go back from definition: xref-go-back
** find functions
space si (This is better than M-x: imenu because it shows results while you navigate too.)
* Images
Below is great documentation for images in emacs.
https://signor.dev/simple-inline-images-in-org-mode/
